import { IAIProvider } from "@/core/ports/ai-provider.port";
import { SummaryResponse } from "@/core/entities/summary.entity";

export class MockAIProvider implements IAIProvider {
  async generateSummary(text: string): Promise<SummaryResponse> {
    await new Promise((resolve) => setTimeout(resolve, 100));

    return {
      title: "Test Title: Mock Implementation",
      summary: [
        "This response is generated by a Mock Provider.",
        "No actual AI request has been made; ideal for testing.",
        "Our system architecture is completely flexible.",
      ],
      tags: ["Test", "Mock", "TypeScript", "Architecture"],
      sentiment: "POSITIVE",
      estimatedTimeToRead: "1 min",
    };
  }
}